=== uladzimirkalesny/java-web-development/task-8/src/main/java/by/epam/training/schema/test5.dtd
<!ELEMENT event (heading+, external-link+, doc-level+)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT external-link (#PCDATA)>
<!ELEMENT doc-level (doc-level*, para+, h1*)>
<!ELEMENT para (#PCDATA|date|image|list-item|num)>
<!ELEMENT h1 (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT image EMPTY>
<!ELEMENT list-item (#PCDATA|para?)>
<!ELEMENT num (#PCDATA)>
<!ATTLIST event id CDATA #REQUIRED>
<!ATTLIST heading type CDATA (title|title-footer) #REQUIRED>
<!ATTLIST external-link source CDATA #REQUIRED>
<!ATTLIST doc-level position (right|left|center|centered) #IMPLIED type #IMPLIED redbox>
<!ATTLIST para type (text|comment|image|unordered-list|num) #REQUIRED style (square|circle) #IMPLIED>
<!ATTLIST image source CDATA #REQUIRED description CDATA #REQUIRED>

=== uladzimirkalesny/java-web-development/task-8/src/main/java/by/epam/training/schema/test5.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--<!DOCTYPE event SYSTEM "test5.dtd">-->
<event id="5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="test5.xsd">
    <heading type="title">Monday's gossip column</heading>
    <heading type="title-footer">Thanks for reading</heading>
    <external-link source="http://www.bbc.com/sport/0/25707984"/>
    <doc-level position="right">
        <doc-level position="left">
            <para type="text">For a list of confirmed transfers, check out the transfers page.</para>
            <para type="text">
                <date>31/12/2013</date>
            </para>
        </doc-level>
        <doc-level position="center">
            <para type="comment">TRANSFER GOSSIP</para>
        </doc-level>
        <para type="image">
            <image source="transfer.jpg" description="Big Spending"/>
        </para>
    </doc-level>
    <doc-level type="redbox">
        <para type="unordered-list" style="square">
            <list-item>Bayern Munich are set to rival Paris St-Germain and Napoli in the race to sign Chelsea attacking
                midfielder Juan Mata, 25.
            </list-item>
            <list-item>Arsenal are planning to offer Â£30m for Newcastle midfielder Yohan Cabaye, 27, and 23-year-old
                full-back Davide Santon.
            </list-item>
            <list-item>
                <para type="unordered-list" style="circle">
                    <list-item>Wolfsburg director of sport Klaus Allofs is confident that a deal has nearly been secured
                        to sign Chelsea midfielder Kevin de Bruyne, 22.
                    </list-item>
                    <list-item>Chelsea boss Jose Mourinho is keen to sign 19-year-old St Etienne defender Kurt Zouma as
                        a long-term replacement for John Terry.
                    </list-item>
                </para>
            </list-item>
        </para>
    </doc-level>
    <doc-level position="center">
        <para type="num">
            <num>2014</num>
        </para>
        <h1>Best year ever</h1>
    </doc-level>
</event>
